import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import joblib
import numpy as np

# # Updated dataset
# data = {
#     "Interests": [
#         "Artificial Intelligence, Robotics", 
#         "Web Development, Data Science", 
#         "Finance, Accounting", 
#         "Environmental Science, Sustainability", 
#         "Architecture, Urban Planning", 
#         "Music, Performing Arts",  
#         "Law, Criminal Justice", 
#         "Healthcare, Medicine", 
#         "Education, Teaching", 
#         "Fashion, Design", 
#         "Robotics", 
#         "Astronomy, Space Exploration", 
#         "Marine Biology", 
#         "Urban Studies", 
#         "Artificial Intelligence, Robotics", 
#         "Finance, Accounting", 
#         "Architecture, Urban Planning", 
#         "Gaming, Virtual Reality", 
#         "Healthcare, Medicine"
#     ],
#     "Strengths": [
#         "Technical Skills", 
#         "Analytical Skills", 
#         "Attention to Detail", 
#         "Problem Solving", 
#         "Creative Expression", 
#         "Artistic Talent", 
#         "Legal Expertise", 
#         "Patient Care", 
#         "Leadership", 
#         "Creative Expression", 
#         "Technical Skills", 
#         "Analytical Skills", 
#         "Research Skills", 
#         "Project Management", 
#         "Technical Skills", 
#         "Attention to Detail", 
#         "Creative Expression", 
#         "Innovation", 
#         "Patient Care"
#     ],
#     "Career Path": [
#         "AI Engineer", 
#         "Data Scientist", 
#         "Financial Analyst", 
#         "Environmental Consultant", 
#         "Architect", 
#         "Musician", 
#         "Game Developer", 
#         "Doctor", 
#         "Teacher", 
#         "Fashion Designer", 
#         "Robotics Engineer", 
#         "Astronomer", 
#         "Marine Biologist", 
#         "Urban Planner", 
#         "Data Scientist", 
#         "Environmental Consultant", 
#         "Architect", 
#         "Lawyer", 
#         "Doctor"
#     ]
# }

# data = {
#     "Interests": [
#         "Artificial Intelligence, Robotics", 
#         "Web Development, Data Science", 
#         "Finance, Accounting", 
#         "Environmental Science, Sustainability", 
#         "Architecture, Urban Planning", 
#         "Music, Performing Arts", 
#         "Gaming, Virtual Reality", 
#         "Law, Criminal Justice", 
#         "Healthcare, Medicine", 
#         "Education, Teaching", 
#         "Fashion, Design", 
#         "Robotics", 
#         "Astronomy, Space Exploration", 
#         "Marine Biology", 
#         "Urban Studies", 
#         "Psychology, Behavioral Science",
#         "Graphic Design, Animation",
#         "Entrepreneurship, Business Management",
#         "Culinary Arts, Nutrition",
#         "History, Archaeology",
#         "Cybersecurity, Information Technology",
#         "Social Work, Community Development",
#         "Economics, Statistics",
#         "Political Science, International Relations",
#         "Photography, Videography",
#         "Journalism, Writing",
#         "Sports, Physical Education",
#         "Quantum Computing, Physics",
#         "Philosophy, Ethics",
#         "Biotechnology, Genetics",
#         "Renewable Energy, Sustainable Development",
#         "Veterinary Science, Animal Welfare",
#         "Nanotechnology, Material Science",
#         "Geology, Earth Sciences",
#         "Astronomy, Astrophysics",
#         "Neuroscience, Cognitive Science",
#         "Human Resources, Organizational Psychology",
#         "Marketing, Digital Marketing",
#         "Supply Chain Management, Logistics",
#         "Mechanical Engineering, Mechatronics",
#         "Civil Engineering, Construction Management",
#         "Artificial Intelligence, Machine Learning",
#         "Oceanography, Marine Science",
#         "Meteorology, Climate Science",
#         "Zoology, Wildlife Conservation",
#         "Linguistics, Language Studies",
#         "Sociology, Anthropology",
#         "Performing Arts, Theater",
#         "Agriculture, Agri-business",
#         "Forensic Science, Criminology",
#         "Interior Design, Home Decor",
#         "UX/UI Design, Human-Computer Interaction",
#         "Blockchain, Cryptocurrencies",
#         "Genomics, Bioinformatics",
#         "Music Production, Sound Engineering",
#         "Virtual Reality, Augmented Reality",
#         "Creative Writing, Poetry",
#         "Game Design, E-sports",
#         "AI Ethics, Tech Policy",
#         "Forestry, Environmental Management",
#         "History of Art, Art Curation",
#         "Classical Studies, Archaeology",
#         "Public Health, Epidemiology",
#         "Urban Gardening, Sustainable Living",
#         "Astrobiology, Exoplanets",
#         "Marine Archaeology, Underwater Exploration",
#         "Robotic Process Automation, AI Operations",
#         "Natural Language Processing, Computational Linguistics",
#         "Theoretical Physics, Particle Physics",
#         "Chemical Engineering, Process Engineering",
#         "Food Science, Nutrition",
#         "Cultural Studies, Anthropology",
#         "Astrophysics, Space Science",
#         "Environmental Policy, Advocacy",
#         "Public Administration, Governance",
#         "Wildlife Conservation, Ecology",
#         "Digital Media, Broadcasting",
#         "Finance, Wealth Management",
#         "Human Rights, International Law",
#         "Criminal Psychology, Behavioral Analysis",
#         "Physical Therapy, Rehabilitation",
#         "Orthopedics, Sports Medicine",
#         "Cardiology, Cardiovascular Research",
#         "Gastroenterology, Digestive Diseases",
#         "Pediatrics, Child Health",
#         "Oncology, Cancer Research",
#         "Immunology, Allergy",
#         "Endocrinology, Hormonal Disorders",
#         "Dermatology, Skin Care",
#         "Neurology, Brain Health",
#         "Psychiatry, Mental Health",
#         "General Surgery, Trauma Surgery",
#         "Plastic Surgery, Aesthetic Medicine",
#         "Anesthesiology, Pain Management",
#         "Radiology, Diagnostic Imaging",
#         "Pathology, Disease Analysis",
#         "Clinical Pharmacology, Drug Development",
#         "Midwifery, Women's Health",
#         "Ophthalmology, Eye Care",
#         "Urology, Renal Health",
#         "Pulmonology, Respiratory Medicine",
#         "Rheumatology, Autoimmune Diseases",
#         "Sports Nutrition, Performance Dietetics",
#         "Biostatistics, Health Informatics",
#         "Bioethics, Medical Ethics"
#     ],
#     "Strengths": [
#         "Technical Skills", 
#         "Analytical Skills", 
#         "Attention to Detail", 
#         "Problem Solving", 
#         "Creative Expression", 
#         "Artistic Talent", 
#         "Innovation", 
#         "Legal Expertise", 
#         "Patient Care", 
#         "Leadership", 
#         "Communication Skills",
#         "Teamwork",
#         "Adaptability",
#         "Critical Thinking",
#         "Strategic Planning",
#         "Public Speaking",
#         "Empathy",
#         "Cultural Awareness",
#         "Data Analysis",
#         "Negotiation",
#         "Conflict Resolution",
#         "Time Management",
#         "Networking",
#         "Mentorship",
#         "Writing Skills",
#         "Entrepreneurial Spirit",
#         "Resilience",
#         "Resourcefulness",
#         "Technical Writing",
#         "Research Skills",
#         "Project Management",
#         "Interpersonal Skills",
#         "Decision Making",
#         "Creativity",
#         "Multitasking",
#         "Detail Orientation",
#         "Innovative Thinking",
#         "Customer Service",
#         "Sales Skills",
#         "Financial Acumen",
#         "Persuasion",
#         "Social Media Management",
#         "SEO Optimization",
#         "Graphic Design",
#         "Audio/Video Editing",
#         "Foreign Language Proficiency",
#         "Coding and Programming",
#         "Database Management",
#         "Cloud Computing",
#         "AI/ML Proficiency",
#         "Robotics Design",
#         "3D Modeling",
#         "Drone Operation",
#         "Geospatial Analysis",
#         "Sustainable Practices",
#         "Ethical Decision Making",
#         "Public Relations",
#         "Event Planning",
#         "Cybersecurity Awareness",
#         "Fitness Training",
#         "Sports Coaching",
#         "Medical Diagnosis",
#         "Clinical Research",
#         "Patient Counseling",
#         "Pharmaceutical Knowledge",
#         "Laboratory Skills",
#         "Chemical Analysis",
#         "Physics Simulation",
#         "Market Research",
#         "User Experience Design",
#         "Brand Development",
#         "Corporate Strategy",
#         "Policy Analysis",
#         "Legislative Writing",
#         "International Negotiations",
#         "Statistical Analysis",
#         "Machine Learning Algorithms",
#         "Human-Computer Interaction",
#         "Bioinformatics Skills",
#         "Robotic Process Automation",
#         "Nanotechnology Expertise",
#         "Genetic Analysis",
#         "Marine Research Skills",
#         "Space Exploration Skills",
#         "Climate Science Analysis",
#         "Marine Biology Techniques",
#         "Epidemiological Analysis",
#         "Public Health Communication",
#         "Biomedical Engineering",
#         "Nursing Expertise",
#         "Surgical Skills",
#         "Therapeutic Techniques",
#         "Rehabilitation Skills",
#         "Neuropsychology Expertise",
#         "Behavioral Analysis",
#         "Organizational Development",
#         "Career Counseling",
#         "Workplace Mediation",
#         "Educational Leadership",
#         "Instructional Design",
#         "Curriculum Development",
#         "Assessment Design",
#         "Pedagogical Expertise",
#         "E-learning Development",
#         "Corporate Training"
#     ],
#     "Career Path": [
#         "AI Engineer", 
#         "Data Scientist", 
#         "Financial Analyst", 
#         "Environmental Consultant", 
#         "Architect", 
#         "Musician", 
#         "Game Developer", 
#         "Lawyer", 
#         "Doctor", 
#         "Teacher", 
#         "Fashion Designer", 
#         "Robotics Engineer", 
#         "Astronomer", 
#         "Marine Biologist", 
#         "Urban Planner", 
#         "Psychologist",
#         "Graphic Designer",
#         "Entrepreneur",
#         "Chef",
#         "Historian",
#         "Cybersecurity Analyst",
#         "Social Worker",
#         "Economist",
#         "Diplomat",
#         "Photographer",
#         "Journalist",
#         "Athlete",
#         "Physicist",
#         "Philosopher",
#         "Biotechnologist",
#         "Sustainability Consultant",
#         "Veterinarian",
#         "Nanotechnology Researcher",
#         "Material Scientist",
#         "Software Developer",
#         "Mechanical Engineer",
#         "Civil Engineer",
#         "Project Manager",
#         "Marketing Manager",
#         "Human Resources Specialist",
#         "Supply Chain Manager",
#         "Digital Marketing Specialist",
#         "Content Creator",
#         "UX/UI Designer",
#         "Blockchain Developer",
#         "Genomics Researcher",
#         "Sound Engineer",
#         "VR Developer",
#         "E-sports Coach",
#         "AI Policy Advisor",
#         "Environmental Manager",
#         "Art Curator",
#         "Archaeologist",
#         "Public Health Official",
#         "Urban Gardener",
#         "Astrobiologist",
#         "Underwater Archaeologist",
#         "AI Operations Specialist",
#         "Computational Linguist",
#         "Theoretical Physicist",
#         "Chemical Engineer",
#         "Food Scientist",
#         "Renewable Energy Engineer",
#         "Climate Scientist",
#         "Zoologist",
#         "Linguist",
#         "Sociologist",
#         "Theater Director",
#         "Agricultural Scientist",
#         "Criminologist",
#         "Interior Designer",
#         "Home Decor Specialist",
#         "Human-Computer Interaction Specialist",
#         "Cryptocurrency Analyst",
#         "Biostatistician",
#         "Clinical Psychologist",
#         "Neuroscientist",
#         "Cognitive Scientist",
#         "Game Designer",
#         "Educational Consultant",
#         "Career Coach",
#         "Corporate Trainer",
#         "Public Speaker",
#         "Legislative Advisor",
#         "International Relations Specialist",
#         "Organizational Psychologist",
#         "Corporate Strategist",
#         "Corporate Lawyer",
#         "Patent Attorney",
#         "Compliance Officer",
#         "Medical Researcher",
#         "Surgeon",
#         "Anesthesiologist",
#         "Cardiologist",
#         "Dermatologist",
#         "Neurologist",
#         "Orthopedist",
#         "Gastroenterologist",
#         "Oncologist",
#         "Endocrinologist",
#         "Ophthalmologist",
#         "Urologist",
#         "Pulmonologist",
#         "Rheumatologist",
#         "Sports Dietitian",
#     ]
# }

data = {
  'Career Path': [
    'AI Engineer', 'AI Engineer', 'Data Scientist', 'Data Scientist', 'Mechanical Engineer',
    'Mechanical Engineer', 'Financial Analyst', 'Financial Analyst', 'Journalist', 'Journalist',
    'Sports Manager', 'Sports Manager', 'Actor', 'Actor', 'Psychologist',
    'Psychologist', 'Diplomat', 'Diplomat', 'Software Developer', 'Software Developer',
    'UI/UX Designer', 'UI/UX Designer', 'Product Manager', 'Product Manager', 'Marketing Specialist',
    'Marketing Specialist', 'Architect', 'Architect', 'Healthcare Specialist', 'Healthcare Specialist',
    'Environmental Scientist', 'Environmental Scientist', 'Entrepreneur', 'Entrepreneur', 'Lawyer',
    'Lawyer', 'Teacher', 'Teacher', 'Journalist', 'Journalist',
    'Civil Engineer', 'Civil Engineer', 'Data Analyst', 'Data Analyst', 'HR Manager',
    'HR Manager', 'Graphic Designer', 'Graphic Designer', 'Nutritionist', 'Nutritionist'
  ],
  'Interests': [
    'Artificial Intelligence, Robotics', 'Web Development, Data Science', 'Web Development, Data Science',
    'Artificial Intelligence, Robotics', 'Physics, Engineering', 'Physics, Engineering',
    'Finance, Accounting', 'Finance, Accounting', 'Creative Writing, Journalism', 'Creative Writing, Journalism',
    'Sports Management, Coaching', 'Sports Management, Coaching', 'Film, Theatre', 'Film, Theatre',
    'Psychology, Sociology', 'Psychology, Sociology', 'Foreign Languages, International Relations',
    'Foreign Languages, International Relations', 'Software Development', 'Software Development',
    'UI/UX Design', 'UI/UX Design', 'Product Management', 'Product Management', 'Marketing',
    'Marketing', 'Architecture', 'Architecture', 'Healthcare', 'Healthcare',
    'Environmental Science', 'Environmental Science', 'Entrepreneurship', 'Entrepreneurship', 'Law',
    'Law', 'Education', 'Education', 'Creative Writing, Journalism', 'Creative Writing, Journalism',
    'Construction, Infrastructure', 'Physics, Engineering', 'Data Science, Business Analysis', 'Data Science, Business Analysis',
    'Human Resources', 'Human Resources', 'Art, Design', 'Art, Design', 'Health, Nutrition', 'Health, Nutrition'
  ],
  'Strengths': [
    'Technical Skills', 'Analytical Skills', 'Technical Skills', 'Creative Expression', 'Analytical Skills',
    'Strategic Thinking', 'Analytical Skills', 'Strategic Thinking', 'Creative Expression', 'Attention to Detail',
    'Leadership', 'Strategic Thinking', 'Artistic Talent', 'Creative Expression', 'Empathy',
    'Cross-Cultural Communication', 'Cross-Cultural Communication', 'Empathy', 'Coding', 'Coding',
    'Design', 'Design', 'Project Management', 'Project Management', 'Marketing', 'Marketing',
    'Creativity', 'Creativity', 'Problem Solving', 'Problem Solving', 'Environmental Awareness',
    'Environmental Awareness', 'Innovation', 'Innovation', 'Legal Knowledge', 'Legal Knowledge',
    'Communication', 'Communication', 'Writing', 'Writing',
    'Engineering Skills', 'Project Management', 'Analytical Skills', 'Problem Solving', 'People Management',
    'Leadership', 'Creativity', 'Design', 'Health Knowledge', 'Empathy'
  ]
}



print(len(data["Interests"]))
print(len(data["Strengths"]))
print(len(data["Career Path"]))
df = pd.DataFrame(data)

# Check the balance of the target variable
# print(df['Career Path'].value_counts())

# Encode the target variable (Career Path)
label_encoder = LabelEncoder()
df['Career Path'] = label_encoder.fit_transform(df['Career Path'])

# Split the data
X = df[['Interests', 'Strengths']]
y = df['Career Path']

# Create a preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('interests', OneHotEncoder(handle_unknown='ignore'), ['Interests']),
        ('strengths', OneHotEncoder(handle_unknown='ignore'), ['Strengths'])
    ])

# Create a RandomForestClassifier with more estimators and a different random_state to see if it helps
model = Pipeline(steps=[('preprocessor', preprocessor),
                        ('classifier', RandomForestClassifier(n_estimators=200, random_state=0))])

# Train the model
model.fit(X, y)

# Test the prediction with different inputs
predicted_class = model.predict(X)

# Save the model and label encoder
joblib.dump(model, 'model.pkl')
joblib.dump(label_encoder, 'label_encoder.pkl')